# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc0f43e05bf39a208870cd1ccc25dd5d86b70352eaaacc6faf7a7f08b3757265ae586343ee2f9abd31742faa702b33eea92c020f10001275ce4fbc6e40ed93cf

test:
  secret_key_base: 26bfff1f0f1d3870bba65d6b9175d5140936e032f1877019bfa1b40d7b9b52126fa68050d12b6be2505e65c9471773a215df66b82528abb0b9d95c7dfa4b4757

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
